### ISSUE TITLE
Can we save audio file after applying filters?

### ISSUE THREAD

**Issue by iosnaresh** [bartolsthoorn/NVDSP#25]
I want to save audio file after applying filters. is this possible?

**Comment by bartolsthoorn** [comment]
Yes, definitely! Novocaine has a great example on how to do that, and since NVDSP works seamlessly with Novocaine, it should be easy to implement it. See [ViewController.mm#L196-L218](https://github.com/alexbw/novocaine/blob/master/Novocaine%20iOS%20Example/ViewController.mm#L196-L218). Please let me know if that works.
