### ISSUE TITLE
How to implement bass boost using high pass filter? any idea?

### ISSUE THREAD

**Issue by arsalananwar** [bartolsthoorn/NVDSP#33]

**Comment by bartolsthoorn** [comment]
The HPF (high pass filter) passes _high_ frequencies, and blocks low frequencies, so it doesn't do the bass boost you want.

I guess you are looking for either _NVHighShelvingFilter_ or _NVLowShelvingFilter_.

The low shelving filter you should set with a positive gain, and with a low frequency. This will boost the lower frequencies, causing a boost in bass. If you boost this into clipping/distortion you need to probably also apply an overall negative gain, to make sure everything stays within limits.

To avoid this potential issue with gain you can use the highshelving filter, and set the frequency above where you want the bass boost to stop and set a negative gain. This will lower everything except the bass. The audio will sound less loud, because everything except the bass is lower in volume, so you have to turn up your overall volume on your speakers, but this is perhaps a safer approach.

Please let me know if this works for you, good luck!

**Comment by bartolsthoorn** [comment]
This is what a high shelving filter looks like. You are interested in the _cut_ version, which is with a negative gain parameter.
![eq-04z](https://cloud.githubusercontent.com/assets/106586/17735571/472a902e-6483-11e6-8a45-e467695c62e3.jpg)

**Comment by arsalananwar** [comment]
il try this, thank you so much :)
