### ISSUE TITLE
Issue with headphones

### ISSUE THREAD

**Issue by arsalananwar** [bartolsthoorn/NVDSP#34]
when i play a song with speakers on and connect the headphones after that, the app crashes in RingBuffer.mm on line number 212. 

outData[i*stride] = mData[whichChannel][idx];

debugging showed that its happening when whichchannel = 1, i tried to hardcord whichchannel = 0 when headphones are connected and the code stopped crashing but then i was getting the audio in really distorted way.

furthermore if we start novocaine with headphones on and play a song and then plug/unplug the headphones, theres no issue there!

**Comment by bartolsthoorn** [comment]
Hmm, this is still unrelated to NVDSP though! Have you tried updating the bundled Novocaine files (such as the RingBuffer.mm) to the latest version from the Novocaine github page?

I will close this for now since RingBuffer.mm is not part of NVDSP but of Novocaine. Please let me know what happens when you update Novocaine and all its files (such as the RingBuffer) though.
